version: '2'

services:
  localteleservices:
    build:
      context: teleservices
      dockerfile: Dockerfile-use-modules-from-git-clones
    image: teleservices-use-modules-from-git-clones:latest
    mem_limit: 2048m
    ports:
        - "80:80"
    extra_hosts:
        local.example.net:
          127.0.0.1
        local-portail-agent.example.net:
          127.0.0.1
        local-agendas.example.net:
          127.0.0.1
        local-auth.example.net:
          127.0.0.1
        local-formulaires.example.net:
          127.0.0.1
        local-documents.example.net:
          127.0.0.1
        local-passerelle.example.net:
          127.0.0.1
        local-hobo.example.net:
          127.0.0.1
        local-stats.example.net:
          127.0.0.1
    volumes:
      - ./data/bijoe:/var/lib/bijoe/tenants
      - ./data/hobo:/var/lib/hobo/tenants
      - ./data/chrono:/var/lib/chrono/tenants
      - ./data/combo:/var/lib/combo/tenants
      - ./data/fargo:/var/lib/fargo/tenants
      - ./data/authentic2:/var/lib/authentic2-multitenant/tenants
      - ./data/wcs:/var/lib/wcs
      - ./data/passerelle:/var/lib/passerelle/tenants
      - ./config/nginx:/etc/nginx/sites-available
      - ./config/chrono:/etc/chrono
      - ./config/combo:/etc/combo
      - ./config/fargo:/etc/fargo
      - ./config/authentic2:/etc/authentic2-multitenant
      - ./config/bijoe:/etc/bijoe
      - ./config/hobo:/etc/hobo
      - ./config/hobo-agent:/etc/hobo-agent
      - ./config/passerelle:/etc/passerelle
      - ./src:/opt/publik
    command: /bin/sh -c "sleep 10 ; /run.sh fromgit"
    depends_on:
      - database
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
  database:
    image: postgres
    hostname: postgres
    volumes:
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_PASSWORD=password"
  memcached:
    image: memcached
    hostname: memcached
