version: '2'

services:
  hobo:
    image: teleservices-jessie-hobo:latest
    volumes:
      - ./data/hobo:/var/lib/hobo/tenants
      - ./config/hobo:/etc/hobo
      - ./config/common/settings.d:/etc/hobo/settings.d
      - ./config/hobo-agent:/etc/hobo-agent
    #  bijoe:
    #    image: teleservices-jessie-bijoe:latest
    #    volumes:
    #      - ./data/bijoe:/var/lib/bijoe/tenants
    #      - ./config/bijoe:/etc/bijoe
  combo:
    image: teleservices-jessie-combo:latest
    volumes:
      - ./data/combo:/var/lib/combo/tenants
      - ./config/combo:/etc/combo
      - ./config/common/settings.d:/etc/combo/settings.d
  fargo:
    image: teleservices-jessie-fargo:latest
    volumes:
      - ./config/fargo:/etc/fargo
      - ./data/fargo:/var/lib/fargo/tenants
      - ./config/common/settings.d:/etc/fargo/settings.d
  authentic:
    image: teleservices-jessie-authentic:latest
    volumes:
      - ./data/authentic2:/var/lib/authentic2-multitenant/tenants
      - ./config/authentic2:/etc/authentic2-multitenant
      - ./config/common/settings.d:/etc/authentic2-multitenant/settings.d
        #depends_on:
        #  - database
  wcs:
    image: teleservices-jessie-wcs:latest
    volumes:
      - ./data/wcs:/var/lib/wcs
      - ./config/common/settings.d:/etc/wcs/settings.d
  passerelle:
    image: teleservices-jessie-passerelle:latest
    volumes:
      - ./data/passerelle:/var/lib/passerelle/tenants
      - ./config/passerelle:/etc/passerelle
      - ./config/common/settings.d:/etc/passerelle/settings.d
    #nginx:
    #  image: nginx:latest
    #  volumes:
    #    - ./config/nginx:/etc/nginx/sites-available
    #  depends_on:
    #    - database
    #    - rabbitmq
    #rabbitmq:
    #  image: rabbitmq
    #  hostname: rabbitmq
    #database:
    #  image: postgres
    #  hostname: postgres
    #  container_name: postgres
    #  volumes:
    #    - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    #  environment:
    #    - "POSTGRES_PASSWORD=password"
    #memcached:
    #  image: memcached
    #  hostname: memcached
