ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION}
ARG DEBIAN_VERSION
# Setting ENV variables
ENV DEBIAN_FRONTEND=noninteractive \
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

# Setting APT parameters
RUN echo "APT::Install-Suggests \"false\";\nAPT::Install-Recommends \"false\";" >> /etc/apt/apt.conf

# Don't allow services to start when building the image
RUN echo "#!/bin/sh\nexit 101" > /usr/sbin/policy-rc.d \
  && chmod +x /usr/sbin/policy-rc.d

RUN apt update && apt install -y \
  apt-transport-https \
  bash-completion \
  ca-certificates \
  cron \
  curl \
  debian-archive-keyring \
  gettext \
  gnupg \
  lftp \
  libreoffice \
  locales \
  nginx \
  procps \
  rsyslog \
  vim-nox \
  zip

# Configure extra repositories
RUN export && echo ${DEBIAN_VERSION}  && echo "deb http://deb.entrouvert.org/ ${DEBIAN_VERSION} main" > /etc/apt/sources.list.d/entrouvert-local.list \
  && echo "deb http://deb.entrouvert.org/ ${DEBIAN_VERSION}-testing main" > /etc/apt/sources.list.d/entrouvert-local.list \
  && echo "deb http://debian.mirrors.ovh.net/debian ${DEBIAN_VERSION}-backports main" > /etc/apt/sources.list.d/backports.list \
  && echo "deb [trusted=yes] https://nexus.imio.be/repository/${DEBIAN_VERSION} ${DEBIAN_VERSION} main" > /etc/apt/sources.list.d/imio.list \
  && cat /etc/apt/sources.list.d/*

RUN curl https://static.imio.be/imio.gpg | apt-key add - \
  && curl https://deb.entrouvert.org/entrouvert.gpg | apt-key add -

RUN cat /etc/apt/sources.list.d/imio.list && apt update && apt install -y \
  entrouvert-repository \
  entrouvert-repository-eobuilder \
  entrouvert-repository-hotfix \
  && apt update && rm /etc/apt/sources.list.d/entrouvert-local.list

RUN echo "Package: *\nPin: release a=$DEBIAN_VERSION-eobuilder\nPin-Priority: 400" > /etc/apt/preferences.d/entrouvert-eobuilder

# Install extra modules
RUN apt install -y authentic2-multitenant
RUN apt install -y  bijoe
RUN apt install -y  chrono
RUN apt install -y  combo
RUN apt install -y  hobo
RUN apt install -y  hobo-agent
RUN apt install -y  passerelle
RUN apt install -y  poppler-utils
RUN apt install -y  prometheus-entrouvert-exporter
RUN apt install -y  publik-base-theme
RUN apt install -y  python3-authentic2-auth-fedict
RUN apt install -y  python3-dns
RUN apt install -y  python3-docutils
RUN apt install -y  python3-magic
RUN apt install -y  python3-passerelle
RUN apt install -y  python3-qrcode
RUN apt install -y  python3-workalendar
RUN apt install -y  wcs-au-quotidien
RUN apt install -y -t $DEBIAN_VERSION-eobuilder imio-publik-themes
RUN apt install -y -t $DEBIAN_VERSION-eobuilder publik-imio-industrialisation
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-combo-plugin-imio-townstreet
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-imio-teleservices-templatetags
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-passerelle-imio-extra-fees
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-passerelle-imio-liege-lisrue
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-passerelle-imio-liege-rn
RUN apt install -y -t $DEBIAN_VERSION-eobuilder python3-passerelle-imio-ts1-datasources
