ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION}
ARG DEBIAN_VERSION
# Setting ENV variables
ENV DEBIAN_FRONTEND=noninteractive \
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8

# Setting APT parameters
RUN echo "APT::Install-Suggests \"false\";\nAPT::Install-Recommends \"false\";" >> /etc/apt/apt.conf

# Don't allow services to start when building the image
RUN echo "#!/bin/sh\nexit 101" > /usr/sbin/policy-rc.d \
  && chmod +x /usr/sbin/policy-rc.d

RUN apt-get update && apt-get install -y \
  apt-transport-https \
  bash-completion \
  ca-certificates \
  cron \
  curl \
  debian-archive-keyring \
  gettext \
  graphicsmagick \
  gnupg \
  lftp \
  libreoffice \
  locales \
  nginx \
  procps \
  rsyslog \
  vim-nox \
  zip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install imio and entrouvert certificates TELE-1927
# Configure extra repositories
RUN curl https://static.imio.be/imio.gpg | gpg --dearmor --yes --output /etc/apt/keyrings/imio.gpg \
  && curl https://deb.entrouvert.org/entrouvert.gpg -o /etc/apt/keyrings/entrouvert.gpg \
  && export && echo ${DEBIAN_VERSION} \
  && echo "deb [signed-by=/etc/apt/keyrings/entrouvert.gpg] http://deb.entrouvert.org/ ${DEBIAN_VERSION} main" > /etc/apt/sources.list.d/entrouvert-local.list \
  && echo "deb [signed-by=/etc/apt/keyrings/entrouvert.gpg] http://deb.entrouvert.org/ ${DEBIAN_VERSION}-testing main" > /etc/apt/sources.list.d/entrouvert-local.list \
  && echo "deb http://debian.mirrors.ovh.net/debian ${DEBIAN_VERSION}-backports main" > /etc/apt/sources.list.d/backports.list \
  && echo "deb [signed-by=/etc/apt/keyrings/imio.gpg] https://nexus.imio.be/repository/${DEBIAN_VERSION} ${DEBIAN_VERSION} main" > /etc/apt/sources.list.d/imio.list \
  && cat /etc/apt/sources.list.d/* \
  && apt-get update && apt-get install -y \
  entrouvert-repository \
  entrouvert-repository-eobuilder \
  entrouvert-repository-hotfix \
  && sed -i 's/deb https/deb [signed-by=\/etc\/apt\/keyrings\/entrouvert.gpg] https/g' /etc/apt/sources.list.d/entrouvert*.list \
  && apt-get update && rm /etc/apt/sources.list.d/entrouvert-local.list \
  && echo "Package: *\nPin: release a=$DEBIAN_VERSION-eobuilder\nPin-Priority: 400" > /etc/apt/preferences.d/entrouvert-eobuilder \
  && apt-get install -y \
  authentic2-multitenant \
  bijoe \
  chrono \
  combo \
  hobo \
  hobo-agent \
  passerelle \
  poppler-utils \
  prometheus-entrouvert-exporter \
  publik-base-theme \
  python3-authentic2-auth-fedict \
  python3-dns \
  python3-docutils \
  python3-magic \
  python3-passerelle \
  python3-qrcode \
  python3-workalendar \
  wcs-au-quotidien \
  && apt-get install -y -t $DEBIAN_VERSION-eobuilder \
  imio-publik-themes \
  publik-imio-industrialisation \
  python3-combo-plugin-imio-townstreet \
  python3-imio-teleservices-templatetags \
  python3-passerelle-imio-extra-fees \
  python3-passerelle-imio-liege-lisrue \
  python3-passerelle-imio-liege-rn \
  python3-passerelle-imio-ts1-datasources \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
