# Dockerfile
FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive

#Update Packages List
RUN echo "APT::Install-Suggests \"false\";\nAPT::Install-Recommends \"false\";" >> /etc/apt/apt.conf
# Don't allow services to start when building the image
RUN echo "#!/bin/sh\nexit 101" > /usr/sbin/policy-rc.d
RUN chmod +x /usr/sbin/policy-rc.d
RUN sed -i "s%httpredir.debian.org%debian.mirrors.ovh.net%g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y nginx wget gnupg debian-archive-keyring rsyslog python-dns gettext vim.nox bash-completion libjs-jquery libreoffice cron lftp
RUN wget -O - http://deb.entrouvert.org/entrouvert.gpg | apt-key add -
RUN echo "deb http://http.debian.net/debian jessie-backports main"> /etc/apt/sources.list.d/backports.list
RUN echo "deb http://deb.entrouvert.org/ jessie main\ndeb http://deb.entrouvert.org/ jessie-eobuilder main\ndeb http://deb.entrouvert.org/ jessie-testing main\n" > /etc/apt/sources.list.d/entrouvert.list
RUN echo "Package: *\nPin: release a=jessie-eobuilder\nPin-Priority: 900" > /etc/apt/preferences.d/jessie-eobuilder.pref
RUN apt-get update
RUN apt install -y -t jessie-backports postgresql-client python-django python-django-common gunicorn python-cryptography
RUN apt install -y -t jessie-testing python-cryptography
RUN apt-get install -y -t jessie wcs-au-quotidien combo fargo hobo bijoe chrono libjs-leaflet passerelle authentic2-multitenant publik-base-theme python-suds python-django-filters
RUN apt-get install -y imio-publik-themes python-authentic2-auth-fedict python-passerelle-imio-liege-lisrue python-passerelle-imio-liege-rn python-passerelle-imio-ts1-datasources python-passerelle-imio-extra-fees python-passerelle-imio-ia-delib -t jessie-eobuilder
# Allow services to start, this is necessary as hobo-agent postinst will fail
# if supervisord is not running
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d
RUN echo "server_names_hash_bucket_size 128;" > /etc/nginx/conf.d/server_names.conf
RUN apt-get install -y -t jessie hobo-agent
# authentic
RUN ln -s /usr/lib/python2.7/dist-packages/authentic2/static/authentic2 /var/lib/authentic2-multitenant/static/
RUN ln -s /usr/lib/python2.7/dist-packages/authentic2/static/jquery /var/lib/authentic2-multitenant/static/
RUN ln -s /usr/lib/python2.7/dist-packages/authentic2/static/ulx /var/lib/authentic2-multitenant/static/
RUN chown -R www-data:www-data /var/lib/authentic2-multitenant/static

#cleanup
RUN rm -f /etc/default/authentic2-multitenant
RUN apt-get -y remove python-dev && apt-get -y autoremove
RUN apt-get clean
RUN mkdir -p /var/lib/authentic2/locale/fr/LC_MESSAGES
COPY mail-translation.py overrides.po /var/lib/authentic2/locale/fr/LC_MESSAGES/
COPY run.sh /
ADD bash-vim.tar.gz /
RUN echo "Europe/Brussels" > /etc/timezone
RUN dpkg-reconfigure tzdata

# Run
CMD ["/run.sh"]
