name: Update images
on:
  schedule:
    - cron: '0 5 * * 0' # Weekly on Sundays at 05:00
  workflow_dispatch:
jobs:
  bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: teleservices-bookworm
        uses: docker/build-push-action@v3
        with:
          context: teleservices
          file: teleservices/Dockerfile-base
          tags: imiobe/teleservices-bookworm-base:latest
          platforms: linux/amd64
          pull: true
          push: true
          build-args: |
            DEBIAN_VERSION=bookworm
