name: Update images
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * 0' # Weekly on Sundays at 05:00
  workflow_dispatch:
jobs:
  buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: teleservices-buster
        uses: docker/build-push-action@v2.5.0
        with:
          context: teleservices
          dockerfile: Dockerfile-base
          image: imiobe/teleservices-buster-base
          tags: latest
          platforms: linux/amd64
          pull: true
          push: true
          buildArgs: |
            DEBIAN_VERSION=buster
  bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: teleservices-bullseye
        uses: docker/build-push-action@v2.5.0
        with:
          context: teleservices
          dockerfile: Dockerfile-base
          image: imiobe/teleservices-bullseye-base
          tags: latest
          platforms: linux/amd64
          pull: true
          push: true
          buildArgs: |
            DEBIAN_VERSION=buster