name: Update images in Harbor
on:
  workflow_dispatch:
jobs:
  bookworm_harbor:
    runs-on:
      group: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.TELESERVICES_HARBOR_USERNAME }}
          password: ${{ secrets.TELESERVICES_HARBOR_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2.5.0
        with:
          context: teleservices
          file: teleservices/Dockerfile-base
          tags: ${{ secrets.HARBOR_URL }}/teleservices/teleservices-bookworm-base:latest
          platforms: linux/amd64
          pull: true
          push: true
          build-args: |
            DEBIAN_VERSION=bookworm
